(ns quadbot.persistence
      (:use [korma.db])
      (:use [korma.core])
      (:use [clojure.test])
      (:require [clojure.java.jdbc :as sql]))

(def dbspec  {:classname   "org.h2.Driver" 
             :subprotocol "h2" 
             :subname "~/.quadbot/db/quadbot"
             :user     "sa"
             :password ""})

(defdb mydb dbspec)
(defentity factoid)

(defn create-tables
  "Create a users table"
  []
  (do 
    (sql/create-table
      "factoid"
      [:id          "IDENTITY" "NOT NULL" "PRIMARY KEY"]
      [:created_by  "VARCHAR(255)"]
      [:fact        "VARCHAR(255)"]
      [:answer      "VARCHAR"]
      [:created_on  "TIMESTAMP" "NOT NULL" "DEFAULT CURRENT_TIMESTAMP"])
   (sql/do-commands "CREATE INDEX FACTIDX ON factoid(fact)")))

(defn drop-tables
  "Drop factoid table"
  []
  (sql/drop-table
    "factoid"))

(defn get-identity
  "Gets the last identity generated by the db"
  []
  (sql/with-query-results rs ["select IDENTITY()"]))

;; Invokes a function with a connection inside a transaction
;; (invoke-with-connection drop-tables)
;; (invoke-with-connection create-tables)
;; (def ident (invoke-with-connection #(insert-factoid "ThaDon" "bleh" "blarg")))
(defn invoke-with-connection [f]
  (sql/with-connection
     dbspec
     (sql/transaction
       (f))))
  
;returns the id of the factoid which was created
(defn insert-factoid [nick fact answer] 
  "(insert factoid) returns a map of {:SCOPE_IDENTITY() <number>} we want the number"
    (invoke-with-connection #(second (first (insert factoid
      (values {:created_by nick :fact fact :answer answer}))
      ))))


(defn delete-factoid [fact]
  (invoke-with-connection #(delete factoid (where {:fact [= fact]}))))

(defn retrieve-factoid [fact]
  (first (invoke-with-connection #(select factoid (where {:fact [= fact]}) (order :created_on :DESC)))))

